//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba1
{
    using System;
    using System.Collections.Generic;
    
    public partial class fuentes
    {
        public fuentes()
        {
            this.proyecto_vs_fuente = new HashSet<proyecto_vs_fuente>();
        }
    
        public int id_fuente { get; set; }
        public string nombre_fuente { get; set; }
    
        public virtual ICollection<proyecto_vs_fuente> proyecto_vs_fuente { get; set; }
    }
}
