//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class prueba1Entities : DbContext
    {
        public prueba1Entities()
            : base("name=prueba1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<fuentes> fuentes { get; set; }
        public DbSet<municipio> municipio { get; set; }
        public DbSet<poblacion> poblacion { get; set; }
        public DbSet<proyecto> proyecto { get; set; }
        public DbSet<proyecto_vs_fuente> proyecto_vs_fuente { get; set; }
        public DbSet<proyecto_vs_poblacion> proyecto_vs_poblacion { get; set; }
    }
}
