//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba1
{
    using System;
    using System.Collections.Generic;
    
    public partial class municipio
    {
        public municipio()
        {
            this.proyecto = new HashSet<proyecto>();
        }
    
        public int id { get; set; }
        public string nombre_mun { get; set; }
    
        public virtual ICollection<proyecto> proyecto { get; set; }
    }
}
