//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba1
{
    using System;
    using System.Collections.Generic;
    
    public partial class proyecto
    {
        public proyecto()
        {
            this.proyecto_vs_fuente = new HashSet<proyecto_vs_fuente>();
            this.proyecto_vs_poblacion = new HashSet<proyecto_vs_poblacion>();
        }
    
        public int Id { get; set; }
        public string codigo_proy { get; set; }
        public string nombre_proy { get; set; }
        public double valor_proy { get; set; }
        public string objetivos { get; set; }
        public Nullable<int> id_municipio { get; set; }
    
        public virtual municipio municipio { get; set; }
        public virtual ICollection<proyecto_vs_fuente> proyecto_vs_fuente { get; set; }
        public virtual ICollection<proyecto_vs_poblacion> proyecto_vs_poblacion { get; set; }
    }
}
