//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba1
{
    using System;
    using System.Collections.Generic;
    
    public partial class proyecto_vs_fuente
    {
        public int id { get; set; }
        public Nullable<int> id_proy { get; set; }
        public Nullable<int> id_fuente { get; set; }
        public Nullable<double> valor_fuente { get; set; }
    
        public virtual fuentes fuentes { get; set; }
        public virtual proyecto proyecto { get; set; }
    }
}
